In [1]:
import requests
import pandas as pd
from datetime import date

BASE_URL = "https://api.boavizta.org/v1"


retrieval_date = date.today().isoformat()

def get_terminal_embodied(device_type):

    response = requests.get(
        f"{BASE_URL}/terminal/{device_type}?verbose=true"
    )

    if not response.ok:
        return None

    data = response.json()

    return {

    "device_category": device_type,

    "te_kgco2eq":
        data["impacts"]["gwp"]["embedded"]["value"],

    "te_min_kgco2eq":
        data["impacts"]["gwp"]["embedded"]["min"],

    "te_max_kgco2eq":
        data["impacts"]["gwp"]["embedded"]["max"],

    "el_hours":
        data["verbose"]["duration"]["value"],

    "el_years":
        data["verbose"]["duration"]["value"]
        / 24
        / 365,

    "source": "boavizta",
    
    "retrieval_date": retrieval_date
}

In [2]:
devices = [
    "laptop",
    "desktop",
    "smartphone",
    "tablet"
]

In [3]:
records = []

for device in devices:

    result = get_terminal_embodied(
        device
    )

    if result:
        records.append(result)

In [4]:
df = pd.DataFrame(records)

df

,device_category,te_kgco2eq,te_min_kgco2eq,te_max_kgco2eq,el_hours,el_years,source,retrieval_date
0,laptop,181.0,181.0,181.0,35040.0,4.0,boavizta,2026-10-13
1,desktop,277.0,277.0,277.0,52560.0,6.0,boavizta,2026-10-13
2,smartphone,84.0,84.0,84.0,21900.0,2.5,boavizta,2026-10-13
3,tablet,75.9,75.9,75.9,26280.0,3.0,boavizta,2026-10-13

Server

In [5]:
response = requests.get(
    f"{BASE_URL}/server/"
)

if response.ok:

    data = response.json()

    records.append({

        "device_category": "server",

        # TE (SCI)
        "te_kgco2eq":
            data["impacts"]["gwp"]["embedded"]["value"],

        "te_min_kgco2eq":
            data["impacts"]["gwp"]["embedded"]["min"],

        "te_max_kgco2eq":
            data["impacts"]["gwp"]["embedded"]["max"],

        # EL (SCI)
        "el_hours":
            data["verbose"]["hours_life_time"]["value"],

        "el_years":
            data["verbose"]["hours_life_time"]["value"]
            / 24
            / 365,

        "source":
            "boavizta",
            
        "retrieval_date": retrieval_date
    })

In [7]:
df.to_csv(
    "boavizta_reference.csv",
    index=False
)

df

,device_category,te_kgco2eq,te_min_kgco2eq,te_max_kgco2eq,el_hours,el_years,source,retrieval_date
0,laptop,181.0,181.0,181.0,35040.0,4.0,boavizta,2026-10-13
1,desktop,277.0,277.0,277.0,52560.0,6.0,boavizta,2026-10-13
2,smartphone,84.0,84.0,84.0,21900.0,2.5,boavizta,2026-10-13
3,tablet,75.9,75.9,75.9,26280.0,3.0,boavizta,2026-10-13
4,server,900.0,459.9,2087.0,35040.0,4.0,boavizta,2026-10-13